### PR TITLE
Bump msrv and unpin cfg-if.

### PR DESCRIPTION
**Pull request by dvc94ch**

### CODE REVIEW

**Comment by soc** [comment]
What's the intention of this?

**Comment by dvc94ch** [comment]
It causes a failure to resolve the dependency if there is another dependency in the graph is using a higher version. Not sure why cargo doesn't include it twice in the dependency graph.

**Comment by dvc94ch** [comment]
So? Do you want me to create a reproducible test case? It's not like I waste my time with PR's to working code

**Comment by soc** [comment]
No, it's fine. I'll probably go the https://github.com/dirs-dev/dirs-rs/pull/26 route and drop cfg-if instead.

**Pull request closed without merging**
