### PR TITLE
Basic Redox OS support

### PR DESCRIPTION
**Pull request by jD91mZM2**
I don't think there's a standard for music/pictures/audio etc yet, but since `env::home_dir` is deprecated now in rust 1.29 it's relatively urgent to get redox support here.

### CODE REVIEW

**Comment by jD91mZM2** [comment]
The latest commit rewrites this PR to use the `redox_users` crate. This is probably the recommended solution, but is unfortunately going to be slower due to quite a few unnecessary allocations. Let me know if you want me to revert it

**Comment by soc** [comment]
@jD91mZM2 Thanks for the PR, I will look into this shortly!

**Comment by soc** [comment]
@jD91mZM2 I squashed and merged your PR, thanks! I also added Redox to the README: https://github.com/soc/dirs-rs/commit/f11123d59e746a65fe976ecbc12d6165938341c6

Does this look fine?

**Comment by jD91mZM2** [comment]
Awesome, thanks! Looks good to me :)

**Comment by soc** [comment]
I have released dirs 1.0.4: https://crates.io/crates/dirs
Let me know if this works for you!

**Comment by jD91mZM2** [comment]
Just tried it, works perfectly. Thanks

**Pull request merged**
