### PR TITLE
Supports wasm32 arch

### PR DESCRIPTION
**Pull request by tiziano88**
Currently the switch only selects `wasi`, which is a special case of
`wasm32`. This change includes the `wasm` mod (renamed from `wasi`) for
any `wasm32` arch.

### CODE REVIEW

**Comment by fkohlgrueber** [comment]
I just came across the same problem. I want to compile `dirs` using the target `wasm32-unknown-unknown` and the current version of `dirs` doesn't compile on that target. 

Using the changes proposed in this PR, it compiles fine. The wasi target (`wasm32-wasi`) is unaffected.

**Comment by soc** [comment]
@tiziano88 thanks for the PR and @fkohlgrueber thanks for doing the research!

**Comment by soc** [comment]
@tiziano88 would you be willing to send the same change also to https://github.com/soc/directories-rs? This would be great, because it would keep the libraries on parity!

**Comment by tiziano88** [comment]
Sure I can do that, but why the duplication? Shouldn't `directories-rs` depend on `dirs-rs` or something like that?

**Comment by soc** [comment]
It uses dirs-rs-sys where code might otherwise be duplicated, but I think this comp. target fix applies to both libraries.

**Comment by fkohlgrueber** [comment]
@soc @tiziano88 I'll do the PR on directories-rs.

**Comment by fkohlgrueber** [comment]
@soc when are these changes going to be released on crates.io? Thanks in advance.

**Comment by soc** [comment]
Hi Felix,

I just released rust-sys 0.3.4, dirs-rs 2.0.2 and directories 2.0.2.

Thanks for the help!

Cheers,
Simon

**Comment by fkohlgrueber** [comment]
Great, thanks very much!

**Comment by jcaesar** [comment]
Doesn't this break behavior wasm32-unknown-emscripten?

**Pull request merged**
